production:
  auto_commit_after_request: false
  solr:
    hostname: ip-10-69-172-218.ec2.internal
    port: 7377
    path: /solr/collection1
    read_timeout: 5
    open_timeout: 1.5
    log_level: INFO
    min_memory: 5G
    max_memory: 7G
    pid_dir: tmp/pids

development:
  auto_commit_after_request: false
  solr:
    hostname: localhost
    port: 7377
    log_level: ALL
    path: /solr/collection1
    pid_dir: tmp/pids


test:
  auto_commit_after_request: false
  solr:
    hostname: localhost
    port: 8982
    log_level: WARNING
    path: /solr/collection1
    pid_dir: tmp/pids

staging:
  auto_commit_after_request: false
  solr:
    hostname: ec2-50-16-197-147.compute-1.amazonaws.com
    port: 7377
    log_level: WARNING
    pid_dir: tmp/pids
    path: /solr/collection1
